// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LobbyPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"text-center bg-gray-800 p-10 md:p-12 rounded-xl shadow-2xl\"><h1 class=\"text-3xl font-medium text-white\">Group Whiteboard</h1><p class=\"text-gray-400 -mt-2 mb-6\">Enter a room name to join or create.</p><div><input type=\"text\" id=\"roomName\" placeholder=\"e.g., 'design-team'\" autocomplete=\"off\" class=\"text-lg p-3 rounded-md border border-gray-600 bg-gray-700 text-gray-100 mr-2 focus:outline-none focus:ring-2 focus:ring-blue-500\"> <button onclick=\"joinRoom()\" class=\"text-lg py-3 px-5 rounded-md bg-blue-600 text-white cursor-pointer transition-colors duration-200 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-800\">Join</button></div></div><script>\n\t\t\tfunction joinRoom() {\n\t\t\t\tconst roomNameInput = document.getElementById('roomName');\n\t\t\t\tlet roomName = roomNameInput.value.trim();\n\t\t\t\tif (roomName) {\n\t\t\t\t\troomName = encodeURIComponent(roomName);\n\t\t\t\t\twindow.location.href = '/room/' + roomName;\n\t\t\t\t} else {\n\t\t\t\t\troomNameInput.focus();\n\t\t\t\t}\n\t\t\t}\n\n\t\t\tdocument.getElementById('roomName').addEventListener('keyup', function(event) {\n\t\t\t\tif (event.key === 'Enter') {\n\t\t\t\t\tevent.preventDefault();\n\t\t\t\t\tjoinRoom();\n\t\t\t\t}\n\t\t\t});\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout("Whiteboard", "h-screen font-sans grid place-items-center bg-gray-900 text-gray-100").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
